apiVersion: v1
kind: Pod
metadata:
  name: application-pod
  labels:
    app: employees
    component: userinterface
spec:
  containers:
    - name: app-container
      image: 671296973118.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:latest-app
      env:
        - name: DBPWD
          value: pass
        - name: DBUSER
          value: root
        - name: DBHOST
          value: "mysql.db-ns.svc.cluster.local"
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080