apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: personnel
    component: userinterface
spec:
  type: NodePort
  selector:
   app: personnel
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32123
 