apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: employees
    component: userinterface
spec:
  ports:
    - port: 8080
  selector:
    app: employees
    component: userinterface