apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        component: db-backend
    spec:
      containers:
      - name: mysql-cont
        image: 671296973118.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:latest-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 3306