apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: 671296973118.dkr.ecr.us-east-1.amazonaws.com/clo835-ecr:latest-mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
      ports:
        - containerPort: 3306